Manage user roles
LykkeCity/Lykke.AlgoStore pull request #88
Opened 2018-04-13 08:57 UTC by todorivanov

2018-04-13 14:33 UTC, ghost requested changes

2018-04-13 14:33 UTC, ghost commented on src/Lykke.AlgoStore.Api/Infrastructure/Attributes/RequirePermissionAttribute.cs
> +    public class RequirePermission : ActionFilterAttribute
- Doesn't need to inherit from ActionFilterAttribute
- Attribute class names should end with Attribute
- The AttributeUsage attribute should be placed on top of attributes to control their usage

2018-04-13 14:33 UTC, ghost commented on src/Lykke.AlgoStore.Api/Controllers/AlgoStoreClientDataController.cs
> +        [RequirePermission]
Consider placing the attribute over the whole controller in cases where all the routes will require permissions

2018-04-13 14:33 UTC, ghost commented on src/Lykke.AlgoStore.Api/Infrastructure/ContentFilters/RequiredPermissionFilter.cs
> +            var needsPermission = context.Controller.GetType().GetMethods().Where(m => m.ReturnType == typeof(Task<IActionResult>) && m.Name == requiredPermission).FirstOrDefault().GetCustomAttribute
You can replace this with (context.ActionDescriptor as ControllerActionDescriptor)?.MethodInfo.GetCustomAttributes

2018-04-13 14:33 UTC, ghost commented on src/Lykke.AlgoStore.Api/Infrastructure/ContentFilters/RequiredPermissionFilter.cs
> +                    if (userRoles[i].Permissions.Find(p => p.Name == requiredPermission) != null)
You can use Any instead of Find here

2018-04-13 14:33 UTC, ghost commented on src/Lykke.AlgoStore.Api/Startup.cs
> +            .Where(t => t.IsClass && t.ReflectedType == null && String.Equals(t.Namespace, "Lykke.AlgoStore.Api.Controllers", StringComparison.Ordinal))
String.Equals() -> t.Namespace == "Lykke.AlgoStore.Api.Controllers"

2018-04-13 14:33 UTC, ghost commented on src/Lykke.AlgoStore.Api/Startup.cs
> +            var permissionsIdsForDeletion = allPermissionIds.Select(p => p.Id).Where(perm => !Permissions.Select(perms => perms.Id).Contains(perm)).ToList();
.Select.Contains -> .Any(perms => perms.Id == perm)

2018-04-13 14:33 UTC, ghost commented on src/Lykke.AlgoStore.Api/Startup.cs
> +                    var matches = allRoles.Where(role => role.Permissions.Select(p => p.Id).Contains(permissionId)).ToList();
Same as above

2018-04-13 14:33 UTC, ghost commented on src/Lykke.AlgoStore.Api/Startup.cs
> +            var userRole = allRoles.Where(role => role.Name == "User" && !role.CanBeDeleted).FirstOrDefault();
.Where( [filter] ).FirstOrDefault -> .FirstOrDefault( [filter] )

2018-04-13 14:33 UTC, ghost commented on src/Lykke.AlgoStore.AzureRepositories/Mapper/RolePermissionMatchMapper.cs
> +            var result = new List<RolePermissionMatchData>();
The whole method can be replaced with entities.Select(entity => new RolePermissionMatchData() ...).ToList(). This will also allow you to take IEnumerable instead of List as an argument

2018-04-13 14:33 UTC, ghost commented on src/Lykke.AlgoStore.AzureRepositories/Mapper/UserPermissionsMapper.cs
> +            var result = new List<UserPermissionData>();
Same changes can be made here as in ToModel in RolePermissionMatchMapper

2018-04-13 14:33 UTC, ghost commented on src/Lykke.AlgoStore.AzureRepositories/Repositories/UserPermissionsRepository.cs
> +            if (result.ToList().Count > 0)
return result.FirstOrDefault()?.ToModel()

2018-04-13 15:43 UTC, dafinkagerdjikova requested changes

2018-04-13 15:43 UTC, dafinkagerdjikova commented on src/Lykke.AlgoStore.Api/Controllers/AlgoStoreUserPermissionsController.cs
> +        public async Task<IActionResult> GetAllpermissions()
It can be -> GetAllPermissions

2018-04-13 15:43 UTC, dafinkagerdjikova commented on src/Lykke.AlgoStore.Api/Controllers/AlgoStoreUserPermissionsController.cs
> +            var result = await _permissionsService.GetPermissionByIdAsync(permissionId);
in this endpoint we return only "Ok" Result, so 
[ProducesResponseType(typeof(BaseErrorResponse), (int)HttpStatusCode.InternalServerError)]
is not requiered, or we need to return BadResponse too.

2018-04-13 15:43 UTC, dafinkagerdjikova commented on src/Lykke.AlgoStore.Api/Controllers/AlgoStoreUserPermissionsController.cs
> +            var result = await _permissionsService.GetPermissionsByRoleIdAsync(roleId);
The same as the previous comment. Should we have an empty result and return "NotFound"?

2018-04-13 15:43 UTC, dafinkagerdjikova commented on src/Lykke.AlgoStore.Api/Controllers/AlgoStoreUserPermissionsController.cs
> +        [ProducesResponseType(typeof(UserPermissionModel), (int)HttpStatusCode.NoContent)]
Is "NoContent" a type  of UserPermissionModel, or there is no model
 [ProducesResponseType(typeof(UserPermissionModel), (int)HttpStatusCode.NoContent)]
[ProducesResponseType((int)HttpStatusCode.NoContent)]
Use only one ProducesResponseType for "NoContent"

2018-04-13 15:43 UTC, dafinkagerdjikova commented on src/Lykke.AlgoStore.AzureRepositories/Mapper/RolePermissionMatchMapper.cs
> +            var result = new List<RolePermissionMatchData>();
It's better to use IEnumerable

2018-04-16 08:24 UTC, iliyan-ivanov-prime commented on src/Lykke.AlgoStore.AzureRepositories/Mapper/UserRoleMatchMapper.cs
> +
Same as above file

2018-04-16 08:24 UTC, iliyan-ivanov-prime commented on src/Lykke.AlgoStore.AzureRepositories/Mapper/UserRolesMapper.cs
> +
Same as above file

2018-04-16 08:26 UTC, iliyan-ivanov-prime commented on src/Lykke.AlgoStore.AzureRepositories/Repositories/RolePermissionMatchRepository.cs
> +
Improving the mapper will result in getting rid of .ToList() here

2018-04-16 08:27 UTC, mjoksa commented on src/Lykke.AlgoStore.Api/Infrastructure/ContentFilters/RequiredPermissionFilter.cs
> +                    if (userRoles[i].Permissions.Find(p => p.Name == requiredPermission) != null)
Just to add on comment above - you can remove for loop and use only one line 
var hasPermission = userRoles.Any(x => x.Permissions.Any(y => y.Name == requiredPermission));

2018-04-16 08:28 UTC, iliyan-ivanov-prime commented on src/Lykke.AlgoStore.AzureRepositories/Repositories/UserRolesRepository.cs
> +             return result.ToList()[0].ToModel();
Same as Iliyan G. comment above

2018-04-16 08:40 UTC, iliyan-ivanov-prime commented on src/Lykke.AlgoStore.Services/UserRolesService.cs
> +                    var userRole = allRoles.Where(role => role.Name == "User" && !role.CanBeDeleted).FirstOrDefault();
Can use only FirstOrDefault(filter)

2018-04-16 08:40 UTC, iliyan-ivanov-prime commented on src/Lykke.AlgoStore.Services/UserRolesService.cs
> +
Remove empty line

2018-04-16 10:06 UTC, mjoksa requested changes

2018-04-16 10:06 UTC, mjoksa commented on src/Lykke.AlgoStore.Api/Infrastructure/ContentFilters/RequiredPermissionFilter.cs
> +            var needsPermission = reflectedMethod.GetCustomAttributes(typeof(RequirePermissionAttribute), false).FirstOrDefault() != null || reflectedMethod.ReflectedType.GetCustomAttributes(typeof(R
This will throw exception if reflectedMethod is NULL. You gotta use
reflectedMethod?.GetCustomAttributes

2018-04-16 10:06 UTC, mjoksa commented on src/Lykke.AlgoStore.Api/Infrastructure/ContentFilters/RequiredPermissionFilter.cs
>                  for (var i = 0; i < userRoles.Count; i++)
You can completely remove  for loop and use LINQ
var hasPermission = userRoles.Any(x => x.Permissions.Any(y => y.Name == requiredPermission));

2018-04-16 10:55 UTC, mjoksa requested changes

2018-04-16 10:55 UTC, mjoksa commented on src/Lykke.AlgoStore.Api/Infrastructure/ContentFilters/RequiredPermissionFilter.cs
>              var reflectedMethod = context.Controller.GetType().GetMethods().Where(m => m.ReturnType == typeof(Task<IActionResult>) && m.Name == requiredPermission).FirstOrDefault();
I think that @iliyan-georgiev-ph mentioned this before, but you can get reflected method like this:
var reflectedMethod = (context.ActionDescriptor as ControllerActionDescriptor)?.MethodInfo;

2018-04-19 14:53 UTC, ghost approved these changes

2018-04-20 07:34 UTC, dafinkagerdjikova approved these changes

2018-04-20 07:39 UTC, mjoksa approved these changes

2018-04-20 08:45 UTC, merged